package com.hw.langchain.llms.ollama;


import com.hw.langchain.llms.base.BaseLLM;
import com.hw.langchain.schema.LLMResult;
import lombok.experimental.SuperBuilder;

import java.util.List;

/**
 * Ollama locally run large language models.
 *
 * @author HamaWhite
 */
@SuperBuilder
public class Ollama extends BaseLLM {
    @Override
    public String llmType() {
        return "ollama-llm";
    }

    /**
     * Call out to Ollama's generate endpoint.
     *
     * @param prompts The prompt to pass into the model.
     * @param stop list of stop words to use when generating.
     * @return The string generated by the model.
     */
    @Override
    protected LLMResult _generate(List<String> prompts, List<String> stop) {
        return null;
    }
}
