# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Publish to Sonatype

on:
  release:
    types: [released]

jobs:
  publish:
  
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Update version
      run: |
        VERSION=$(echo "${{ github.ref }}" | sed -e 's/refs\/tags\/v//')
        mvn versions:set -DnewVersion="${VERSION}"
        
    - name: Publish to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: mvn deploy
